name: CI – Build Spring Boot Starter ORD

on:
  push:
    branches:
      - 'main'
      - 'rel/**'

jobs:
  build:
    name: Build Spring Boot Starter ORD
    runs-on: ubuntu-latest
    steps:

      - name: Checkout spring-boot-starter-ord repo
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.21.0
        with:
          java-version: 17
          maven-version: 3.9.14

      - name: Build project
        run: mvn clean install -B -Dgpg.skip=true
